### ISSUE TITLE
Fatal runtime error - EXCEPTION_ACCESS_VIOLATION (v0.0.3)

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#11]
When i first run the script (no local folders or buckets of goobox) it gives the following output on windows 10:
```
Checking if local Goobox folder exists... no. Folder created.
Checking if Goobox config folder exists... no. Folder created.
Checking if cloud Goobox bucket exists... no. #
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000077615a9c, pid=11204, tid=2224
#
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.1+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.1+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x685a9c]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\meije\Downloads\goobox-sync-storj-0.0.3-win64\goobox-sync-storj\hs_err_pid11204.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Press any key to continue . . .
```

Logs:

[hs_err_pid1500.log](https://github.com/GooBox/goobox-sync-storj/files/1442586/hs_err_pid1500.log)
[hs_err_pid11204.log](https://github.com/GooBox/goobox-sync-storj/files/1442587/hs_err_pid11204.log)

**Comment by MeijeSibbel** [comment]
Ok so it appears i only get the issue when i delete the bucket. If i just remove the `GooBox` and `.goobox` folders then i don't get the error and i get this:

```
Checking if local Goobox folder exists... no. Folder created.
Checking if Goobox config folder exists... no. Folder created.
Checking if cloud Goobox bucket exists... yes
Checking for changes...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sleeping for 1 minute...
```

**Comment by kaloyan-raev** [comment]
Perhaps, I messed up something with the JNI code for creating new bucket. It's good that it is easily reproducible.

**Comment by MeijeSibbel** [comment]
[hs_err_pid14408.log](https://github.com/GooBox/goobox-sync-storj/files/1442615/hs_err_pid14408.log)

**Comment by kaloyan-raev** [comment]
I nailed the issue down to libstorj. The metadata returned by the `storj_bridge_create_bucket` has the `created` property as uninitialized pointer, i.e. pointing the a random point the memory. Hence, its behavior is unpredictable - sometimes it can point to a random, but valid string, otherwise to a point in the memory that does not represent a string. In the latter case, the program will crash.

I will report the issue to libstorj and will provide a patch.

**Comment by MeijeSibbel** [comment]
Glad you found the issue!

**Comment by kaloyan-raev** [comment]
https://github.com/Storj/libstorj/pull/400

**Comment by MeijeSibbel** [comment]
PR has been merged to Libstorj master, closing.
