### ISSUE TITLE
Synchronized icon doesn't appear on macOS

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-sync-storj#113]
![screenshot](https://user-images.githubusercontent.com/1793096/38140536-24c3a4e4-3402-11e8-9b98-250d4a0f06ca.png)
[log.txt](https://github.com/GooBox/goobox-sync-storj/files/1863784/log.txt)

**Comment by kaloyan-raev** [comment]
@jkawamoto I am not sure how to reproduce this. 

Does it happen on Windows?

What's the DB state of the files with no overlay icon? Is any of them syncing too?

**Comment by jkawamoto** [comment]
The DB state is as same as one in #114 and the outputs of dump command is [here](https://github.com/GooBox/goobox-sync-storj/files/1885837/list_db.txt).

On Windows, it didn't happen.

**Comment by kaloyan-raev** [comment]
I cannot see any issue in the code. The only thing I noticed in the logs is that the `OK` icon is registered first. Perhaps, you can try changing the registration order, so the `OK` icon is not first, and see if this makes any difference.

**Comment by jkawamoto** [comment]
Initializing icons in reverse order worked to show sync icons. But, this time, the app loses the error icons...

**Comment by jkawamoto** [comment]
I've tried to wait 10 more seconds before registering overlay icons and so far it works. I'll open a PR about this in the common library's branch.
