### ISSUE TITLE
Feature: Parallel uploading and downloading to maximize bandwidth utilization -> reduces sync time

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#12]
When someone drops more than one file into the sync folder the app should try to sync as many files to the cloud simultaneously as possible to ensure minimum sync times and maximum bandwidth utilization.

Though we should be careful with this as uploading too many files at once (depending on the size of the file) can cause the system to slow down to the point it becomes noticeable to the user, which should be avoided at all costs. Something like dynamic host resource monitoring and adjusting concurrency appropriately would do the trick, though this is a bit more advanced.

**Comment by kaloyan-raev** [comment]
I'd rather leave this for the long term plan. The promise of Storj is to be faster than the traditional cloud. Of course, this promise is not delivered yet due to various reasons: lack of federated bridge, pure farmer rating, big shards, etc. However, AFAIK, libstorj already use parallel upload/download for the different shards.

Let's revisit this idea when we have the basics of Goobox ready and stable. And see where Storj stands at that point.

**Comment by MeijeSibbel** [comment]
I agree, its only really relevant for small files, so right now when uploading say a 1MB file, it will take 3-10 seconds before it starts upload due to the time it takes for contract negotiation with the bridge and the farmer(s), so if you have 1000x 1MB files, it can take a very long time simply because contract negotiation takes a long time and it has to do it for every single file. The bigger the files the less of an issue this becomes.

**Comment by MeijeSibbel** [comment]
To add to this, with sub-directory support, if a user has a bunch of folders with many sub-folders, uploading the 1 byte directory files takes about 30-60 seconds for each file. This makes sync times even with a few sub-directories gruelingly slow. The issue here is not really the transfer speed that is slow, its the time it takes to handle a contract request by the bridge before uploading start. Although this can be improved by for example https://github.com/Storj/bridge/issues/528, it will, for the foreseeable future still take a few seconds per file. This means that for many small files like photos, sync times can take a very long time. Stefan suggested to  find a midway, `"make a threaded upload depending on the amount of logical cores, Storj the Share does."`, this sounds like a good idea to at least bring sync times down to a acceptable level. Users's aren't going to wait around 2 hours for a 1MB or so folder to sync and Storj isn't going to find a quick-fix in the foreseeable future also.

Since each user can make about 1000x API requests per minute, we can easily parallel upload tens of files at the same time multithreaded. I am referring to uploading multiple files at the same time, not multiple shards at the same time, that is already multithreaded.

So maybe we can just fire up one upload per logical CPU core.

**Comment by jasonwee** [comment]
For this issue, if we have to use the core, maybe we should use [ExecutorService](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newFixedThreadPool-int-])?

But given this [gist](https://gist.github.com/jasonwee/8e3e2595b48c8b56313f962474ee8a17), the upload is done and follow by another task. I was curious if the sequence matter. If the files upload and/or download has correlation between each other?

Maybe this I can start to come out with a prototype using the ExecutorService, we can see how it goes?

**Comment by MeijeSibbel** [comment]
@kaloyan-raev ^

**Comment by kaloyan-raev** [comment]
No, there is no correlation. When implementing parallel task execution, it should be done with great care on the synchronization on the sync db and task execution queue.

**Comment by jasonwee** [comment]
work done already merged, closing issue
