### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#22]
````
   97%         6195116/6326188 bytes
   98%         6211500/6326188 bytes
   98%         6227884/6326188 bytes
   98%         6244268/6326188 bytes
   98%         6260652/6326188 bytes
   99%         6277036/6326188 bytes
   99%         6293420/6326188 bytes
   99%         6309804/6326188 bytes
  100%         6326188/6326188 bytes
  done.
Uploading file paper.docx...
    0%               0/0 bytes
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006df82355, pid=31516, tid=7036
#
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.1+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.1+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [libjson-c-3.dll+0x2355]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\meije\Downloads\goobox-sync-storj-0.0.4-win64\goobox-sync-storj\hs_err_pid31516.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Press any key to continue . . .
```

**Comment by MeijeSibbel** [comment]
[hs_err_pid31516.log](https://github.com/GooBox/goobox-sync-storj/files/1456065/hs_err_pid31516.log)

**Comment by kaloyan-raev** [comment]
How often did it happen? Only once?

Could you give more details how it happened? I see it is during uploading file... but how many files did it upload before crashing?

I need to reproduce it in order to investigate it.

**Comment by MeijeSibbel** [comment]
It only happened once up to now but i am trying to reproduce it, it will let you know once i am able to reproduce it. It happened during uploading, i dragged some files into the folder, the first 3x uploads went fine, it then crashed at the 4th one. I have a feeling the bridge returned a error that the app didn't catch (e.g. bridge rate limit error or failed to find offers), but am not sure.

**Comment by kaloyan-raev** [comment]
This happened to me several times today on Windows. Not during file upload, but during app start - while retrieving the list of buckets.

I am attaching the crash log for reference.
[hs_err_pid4676.log](https://github.com/GooBox/goobox-sync-storj/files/1491564/hs_err_pid4676.log)

**Comment by kaloyan-raev** [comment]
I was able to generate minidump file (200 MB) using the `-XX:+CreateMinidumpOnCrash` options as described [here](https://stackoverflow.com/a/34842953/2356099).

I also install [WinDbg](http://windowscoding.com/blogs/blake/archive/2009/05/12/opening-a-mini-dump-file-mdmp-file-with-WinDbg.aspx), which is supposed to open it.

For now it just reports that debug symbols cannot be found. My next step is to recompile all native libraries with debug symbols and try again.

**Comment by kaloyan-raev** [comment]
After doing some dark magic with WinDbg I have a native stack trace with some more details:
```
libjson_c_3!json_object_put+0x5
libstorj_1!storj_free_get_buckets_request+0x1c
storj_java+0x1a88
libuv_1!uv__work_done+0xa5
libuv_1!uv_run+0xfe
storj_java!Java_io_storj_libstorj_Storj__1getBuckets+0xed
```
Now I know that the crash happens when calling the `json_object_put` function from `storj_free_get_buckets_request`. I can see in the Java binding that there is another call to `json_object_put` just before calling `storj_free_get_buckets_request`. So `json_object_put` is actual called twice. This function is responsible for releasing the memory allocated for a JSON object. It seems that calling it twice is not safe and may occasionally cause such crash.

I will carefully verify the libstorj code and the Java binding to avoid such double calls.

**Comment by kaloyan-raev** [comment]
Fix in the Java binding: https://github.com/kaloyan-raev/java-libstorj/commit/aab75afe6f188215bd4d5e4b70e3095dd558e95f

**Comment by kaloyan-raev** [comment]
PR for libstorj: https://github.com/Storj/libstorj/pull/403

**Comment by kaloyan-raev** [comment]
PR for libstorj merged.
Closing.
