### ISSUE TITLE
Display status icon on files and folders in Windows Explorer

### ISSUE THREAD

**Issue by kaloyan-raev** [GooBox/goobox-sync-storj#3]
The `Goobox` sync folder and its files and subfolders shall be decorated with a small status icons. The icon shall tell the user if a file or folder is:
- Already synced (e.g. green tick icon)
- In the progress of being synced (e.g. blue icon with arrows)
- Failed to sync (e.g. red cross icon)

**Comment by MeijeSibbel** [comment]
@paisana15 , here are a couple of links i could find on this:

Github links: 

https://github.com/owncloud/client/tree/47fbfbc006c1d9ba3b23580bc86309429b995c59/shell_integration/windows/OCOverlays
https://github.com/liferay/liferay-nativity/blob/master/README.md
https://github.com/kirked/dropbox-status-icons

Other links: 

https://stackoverflow.com/questions/8383668/add-status-icons-over-file-icons-in-explorer-like-dropbox-or-svn-in-net
https://www.quora.com/How-does-Dropbox-add-status-icons-over-files
https://www.garethjmsaunders.co.uk/2015/03/22/managing-overlay-icons-for-dropbox-and-tortoisesvn-and-tortoisegit/

A list of overlay icons can be found here: 

https://github.com/owncloud/client/tree/47fbfbc006c1d9ba3b23580bc86309429b995c59/shell_integration/windows/OCOverlays/ico

**Comment by paisana15** [comment]
Thanks for the update. I'll start with the search.

**Comment by kaloyan-raev** [comment]
https://github.com/liferay/liferay-nativity is definitely the nugget from all these links. This library will do the job.

**Comment by kaloyan-raev** [comment]
After some thought on the two-way sync, I believe we need a 4th state - "Conflict". This would be the state where both the local and cloud copy of a file has been changed while the sync app was down, or while the device had no internet connection. At this state the sync app cannot decide for the user which copy should be copied over the other. Manual action by the user will be required to resolve the conflict.

**Comment by MeijeSibbel** [comment]
Something like this: https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-wcstatus.html.

This overlay looks better though: https://github.com/owncloud/client/blob/47fbfbc006c1d9ba3b23580bc86309429b995c59/shell_integration/windows/OCOverlays/ico/Warning.ico , the red exclamation mark is just too intense. 

We should not interfere too much with the user activity by giving them all sorts of info, things should stay simple and intuitive.  I like your context menu in the file explorer idea.

**Comment by MeijeSibbel** [comment]
With some more digging around it appears that there is a limit of 15 overlay icons in windows 10, meaning that if you have OneDrive, Dropbox installed, there will be no more room for the Goobox overlay icons. I am not 100% sure but we might be forced to re-use the overlays already in the registry.

Also relevant to https://github.com/GooBox/goobox-sync-storj/issues/2

As explained here:
* https://support.microsoft.com/en-us/help/3079213/sync-icon-overlays-are-missing-from-onedrive-and-onedrive-for-business
* https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/10402716-sync-overlay-icons-shelliconoverlayidentifiers-l

**Comment by MeijeSibbel** [comment]
Alright so this is exactly what they also say in liferay java library:

```
Limitations and Issues

Windows limits the total number of icon overlays to 15. Windows uses 4-6 of these, so only 9-11 remain for use by other applications. If you use other applications like Dropbox or TortoiseSVN, your icon overlays may not appear (Windows will load the first 15 icon overlays alphabetically).

You can see the your list of registered icon overlays by navigating to the following registry key HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers.
```
So this is definitely a issue.

**Comment by jkawamoto** [comment]
@kaloyan-raev, could you implement this function in goobox-sync-common so that goobox-sync-sia can use it?

**Comment by kaloyan-raev** [comment]
The DLLs for the overlay icons require that the [Microsoft Visual C++ 2010 Redistributable Package (x64)](https://www.microsoft.com/en-US/download/details.aspx?id=13523) is installed on the system. Otherwise they fail registering.

**Comment by jkawamoto** [comment]
Can the native installer install the package?

**Comment by kaloyan-raev** [comment]
Yes, this is a task for the native Windows installer.

**Comment by kaloyan-raev** [comment]
This is now implemented for Windows only. Other OS types require building the respective native libraries and adjusting the Java code a bit.
