### ISSUE TITLE
Two-way sync

### ISSUE THREAD

**Issue by kaloyan-raev** [GooBox/goobox-sync-storj#4]
Version 0.0.2 introduced one-way sync, i.e. the state of the cloud is replicated to the local sync folder.

This shall be improved with a two-way sync. Changes between the cloud and the local sync folder should be replicated depending on where the user has made the change.

**Comment by MeijeSibbel** [comment]
At each file upload a `Created: 2017-10-30T21:43:27.658Z` is returned by Libstorj, this should help to track at what point in time the last change was made to a specific file (at what point it was re-uploaded). Comparing this with a local "last change" record of the uploaded files during the last sync in the sync folder should allow to determine if and when a change was made and where.

**Comment by kaloyan-raev** [comment]
Timestamps are tricky. Consider this example:
1. Create a file in the local Goobox folder.
2. The file will by synced to the remote Storj bucket. Inevitable it will take some time, so the Created timestamp of the Storj copy will be some time later than the Created/Modified date of the local copy.
3. The sync app will see that the Storj copy has a newer timestamp than the local copy. So, it will start copying the file (although not changed) from Storj to the device. As this takes time too, now the local copy will have a last modified date a little bit newer than the Created timestamp of the Storj copy.
4. Go to point 2.

I think we need some sort of a local database where the sync app keeps track on the last known state on both the local sync folder and the Storj bucket. This way, whenever it finds a difference between the two copies it can check the database and see where is the actual origin of the change. The database can also keep track for failures (e.g. partially downloaded files) and conflicts.

As far as I can see Dropbox also maintains a database - in the `<user-home>/.dropbox` folder.

**Comment by kaloyan-raev** [comment]
This was implemented in version 0.0.3. Further improvements will be tracked in separate issues.
