### ISSUE TITLE
Automatic conflict resolution

### ISSUE THREAD

**Issue by kaloyan-raev** [GooBox/goobox-sync-storj#40]
I gave some thought on resolving conflicts and I am going to outline my ideas here.

First, what is a conflict for the sync app? Conflict is when a file has both a copy on the local storage and in the cloud (Storj, SIA, etc.), the file is not in `synced` state and it is not obvious (for the sync app) where the user made the change: locally on the current device, or from another device (and that changed was synced to the cloud).

As part of the conflict resolution the sync app already maintains a sync database on the local device to keep track of the changes that occur both locally and in the cloud. Then, if a new change is detected (locally or in the cloud), the sync app compares the file timestamps with those in the sync database, and makes a decision which direction to make the file transfer to.

The sync database is good solution for most of the use cases. But there are still some that require additional decision making:
- A new file appears simultaneously both locally and in the cloud, but there is no entry in the sync database. This may happen if 1) the sync app has been temporarily stopped; 2) there has been an Internet connection outage; 3) the user deleted the sync database for some reason.
- A file is modified simultaneously both locally and in the cloud, and there is an entry in the sync database for this file. This may happen for the same reasons above, but also if two users are editing the same file simultaneously.

There are two possible ways to handle the above situations:
- Manual. Prompt the user with a dialog describing the conflict and ask him to make the decision.
- Automatic. Try to resolve the conflict without bothering the user.

There are pros and cons for both approaches. Asking the user is safer that any valuable data won't be lost. But asking too much can be quite annoying. I don't really expect many situations like multi-user editing of a file, so at least for the beginning we can provide only automatic resolution. Upon real user requests we can later provide the option for manual conflict resolution. Having the conflicts resolved automatically will let us avoid maintaining a conflict state in the sync database. This will significantly simplify the sync logic.

The algorithm for automatic conflict resolution would be like this:
1. Check if the local and cloud copy of the file are equal. For now, we can check their size. It's not completely accurate, but would work most of the time. Later when #29 is resolved, we can use the HMAC for 100% accuracy.
1.1. If the copies are equal then mark the file as synced in the sync db. Conflict resolved.
2. Otherwise, check last modified / created timestamps of the local and cloud copy.
2.1. If the cloud copy has a more recent timestamp, transfer it over the local copy.
2.2. If the local copy has a more recent timestamp, transfer it over the cloud copy.
2.3. In the extremely unlikely event of exactly equal timestamps, transfer the cloud copy over the local copy.
2.4. Update the sync db after the successful file transfer. Conflict resolved.

**Comment by kaloyan-raev** [comment]
@MeijeSibbel what do you think about this?

**Comment by MeijeSibbel** [comment]
Nice write-up!, i completely agree that automatic conflict resolution is the way to go now, not only because its easier to implement as you mentioned, but also because it improves on the user experience overall. I also really like the  automatic algorithm, makes complete sense to do it like that. lets go for it.

**Comment by MeijeSibbel** [comment]
@kaloyan-raev ,btw this is also relevant for @jkawamoto as its obviously essential to use the same logic (or very similar) across both facets of the app.

**Comment by kaloyan-raev** [comment]
Yes, I guess it would be similar for SIA. Although, I am not sure right now what metadata info is available for the files stored in the SIA cloud.

**Comment by jkawamoto** [comment]
From [SIA's API document](https://github.com/NebulousLabs/Sia/blob/master/doc/api/Renter.md#renterfiles-get), only filesize is provided as metadata. But, I think we can embed a timestamp in filepath, eg. `foo/bar.txt/<UNIX time>`. I'm not sure how long siapath is acceptable but it might be possible to embed HMAC, too.

**Comment by kaloyan-raev** [comment]
@jkawamoto I am not in favor of embedding metadata in the file name or path. This is incompatible with other apps users may use for uploading/download file from SIA. Perhaps, it's best to open an issue on SIA and request they store additional metadata like:
- upload timestamp
- integrity checksum (even a simple MD5 would be enough)

**Comment by MeijeSibbel** [comment]
This was the answer i got from one of the SIA community developers on this:

```
i think the uploading application is supposed to keep track of checksums
would be nice if sia supported it too though
pixeldrain keeps sha256 sums in a mariadb
```

`Sia does have checksums internally I think, so in theory the file cannot be modified by hosts`

**Comment by jkawamoto** [comment]
This is a closed issue but when I implement your algorithm to sync sia app, I am wondering if a local file is modified and then the corresponding cloud file is also modified, check state task would decide to download the newer cloud file and the local change would be overwritten. It seems a rare case but might happen when a sync app is offline for a long time.

**Comment by kaloyan-raev** [comment]
Yes, this is the current logic of the automatic conflict resolution. If you see my initial description in this issue, there is some trade off. Later we can introduce manual conflict resolution for those situations where there is a potential data loss. It will require significantly more development effort.

**Comment by jkawamoto** [comment]
In such a case, for example Dropbox and Evernote keep both files and the name of the old file is modified to have a description about the conflict. I agree we currently don’t need the manual solution you describe in https://github.com/GooBox/goobox-sync-storj/issues/40#issue-274456768 but I think at least we should keep the ole files.

**Comment by kaloyan-raev** [comment]
Could you open a new issue describing the exact algorithm to apply in this specific use case?

**Comment by jkawamoto** [comment]
Sure.
