### ISSUE TITLE
Exclude system and temporary files

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-sync-storj#51]
As we discussed in https://github.com/GooBox/goobox-sync-sia/issues/15#issuecomment-347338556, following files should be excluded:
- system files: `desktop.ini`, `thumbs.db`, `.ds_store`, 
- temporary files:
  - file its name starts with `~$` or `.~`,
  - file its name starts with `~` and ends with `.tmp`
- files and directories their names end with spaces.

**Comment by kaloyan-raev** [comment]
I implemented this in a way that only system and temp files added locally to the sync folder are excluded for upload. If the Goobox folder in the Storj bridge has such files, they will still be synced locally.
