### ISSUE TITLE
Don't allow the uploading of 0 byte files

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#59]
I was experimenting some more to get it to break and this was one of the strange output: 

These files were already sync'd to the folder a few days ago. 

```
Checking if local Goobox sync folder exists... yes
Checking if Goobox data folder exists... yes
Checking if cloud Goobox bucket exists... yes
Checking for changes...
Deleting old version of PicOfTheDay/iss053e047067.jpg on the cloud... done
Uploading file PicOfTheDay/iss053e047067.jpg...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of HeidiSQL/PicOfTheDay/pia21353-1041.jpg on the cloud... done
Uploading file HeidiSQL/PicOfTheDay/pia21353-1041.jpg...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of random/A1066.tmp on the cloud... done
Uploading file random/A1066.tmp...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of random/A1113.tmp on the cloud... done
Uploading file random/A1113.tmp...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of random/A1129.tmp on the cloud... done
Uploading file random/A1129.tmp...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of random/A1201.tmp on the cloud... done
Uploading file random/A1201.tmp...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of random/A1205.tmp on the cloud... done
Uploading file random/A1205.tmp...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of random/A1263.tmp on the cloud... done
Uploading file random/A1263.tmp...
    0%               0/0 bytes
  Upload failed. File size error (3003)
Deleting old version of A10.tmp on the cloud... done
Uploading file A10.tmp...
    0%               0/0 bytes
  Upload failed. File size error (3003)
```

**Comment by kaloyan-raev** [comment]
Indeed, this is strange. Has really any of these files 0 byte size on the local drive?

Have you done anything special to trigger this?

**Comment by MeijeSibbel** [comment]
yeah somehow some of the files were 0 bytes, though i don't know how they got to be 0 bytes since it downloaded them from the cloud. Lets keep this open until i can reproduce it.

Edit: maybe cancelling a file while its downloading causes a 0 byte file to stay behind?

**Comment by MeijeSibbel** [comment]
sync-storj shouldn't allow uploading 0 byte files, if it does maybe make a full shard of the file?

**Comment by jasonwee** [comment]
https://gist.github.com/jasonwee/c698a447353b23692a0492b446aac76d when I upload an empty file, the error shown `Upload failed: File size error (3003)`, so not sure how you are able to download an empty file from cloud. I have also list using command line storj to verify if the empty file is created on cloud (which it does not see if you read the gist)

For this issue, should we do a check if the file size is empty, then don't create a new `UploadFileTask`?

**Comment by MeijeSibbel** [comment]
Kaloyan^^

**Comment by kaloyan-raev** [comment]
@jasonwee Yes, there is a check in libstorj if the file size is 0. If it is, libstorj returns that `File size error`. What you suggest seems like a good workaround of this limitation.

**Comment by jasonwee** [comment]
okay, great.
