### ISSUE TITLE
handle Internet dropout during sync

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#60]
If the internet connection drops while it is uploading, it will end up in a endless loop with: 
`"Error checking in file name <file_name> exits: request failed with status code 0. Trying again....". It is good that it retries, but it does so multiple times a second in a uncontrolled manner, or at least that is what it looks like. If this is not the case feel free to close the issue. I would expect it to retry say once a second.

**Comment by kaloyan-raev** [comment]
This is resolved with https://github.com/GooBox/goobox-sync-storj/commit/233599d7f5dab5db9715d2feea241797f23526bf. Now there will be a 3 seconds sleep between attempts.
