### ISSUE TITLE
Can't delete, rename or move file in sync folder while uploading it to storj.

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#63]
Users shouldn't be blocked from deleting, moving or renaming files while they are uploading, this will irritate people as they can't interact with their files. If a user deletes a file while its being uploaded, cancel the upload. If its renamed when uploading, cancel the upload, if a user moves the file while uploading, cancel the upload. Then upload it again once the user is done with the task..

![image](https://user-images.githubusercontent.com/11735738/33955851-33d2d61c-e03d-11e7-82a6-5b30152922fc.png)
![image](https://user-images.githubusercontent.com/11735738/33956217-3141779a-e03e-11e7-9938-8d5ff66d81e1.png)

related to: 

https://github.com/GooBox/goobox-sync-sia/issues/25
https://github.com/GooBox/goobox-sync-sia/issues/26

**In sync-sia this was implemented in the following way:** https://github.com/GooBox/goobox-sync-sia/commit/6ce86c5f76e8af70eec345d1e6d1a0822bd61849

**Comment by MeijeSibbel** [comment]
Alternatively something like copying it to %temp% and uploading the file from there might also work

**Comment by jasonwee** [comment]
I don't see how does a file hashing calculation is a solution for the file in use error complaint by windows (need explanation)? From Meije's windows, it seem that the error file in use only happen when file in sync, meaning during file uploading, hence `UploadFileTask`. Perhaps we should really consider the idea above, that the class [Files](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempFile-java.nio.file.Path-java.lang.String-java.lang.String-java.nio.file.attribute.FileAttribute...-) , create a temporary file of the actual file and use this temporary file to upload. While file upload in progress, we check the actual file for modification (e.g. rename, remove, move), and if the file encountereted any of the three changes, then repeat the upload process again. workable idea?

~~This can be a problem, cause I'm not sure how to upload the test jar to windows for testing purposes.~~
lol.. we should use what we have built! , transfer goobox sync, transfer the jar to `C:\Program Files\Goobox\resources\app\goobox-sync-storj`

**Comment by jasonwee** [comment]
okay, the cancel upload feature branch has merge, I will now work on the file in use error by windows

**Comment by jasonwee** [comment]
Regarding message '...file in use by java platform...', after investigations and findings, the following conclusion were drawn:
* tested only windows and it is specific to windows only.
* https://github.com/GooBox/goobox-sync-storj/pull/123 tested works fine for linux
* no mac, so can't test. anyone with mac, please test

We can specify option when opening the file in java as indicated [here](https://stackoverflow.com/questions/2537306/java-opening-and-reading-from-a-file-without-locking-it) indifferent with the current implementation of `UploadFileTask` is by calling the native cpp api.

After further discussion with Kaloyan, the following implementation is desire. A possible way to work this around is to make a temp copy of the file and do the upload from the copy. Then if the original file is moved or deleted during upload you can still cancel it.

But there is an disadvantage where disk usage increase during temporary file creation and this is visible given the example in this issue where size of file exceed 2GB. But usually this is not an issue on desktop and it might be on mobile but this is not our case.

**Comment by MeijeSibbel** [comment]
@jkawamoto has a Mac if i am not mistaken, maybe he can help out.

**Comment by jkawamoto** [comment]
sync-storj v0.0.27 doesn't interrupt deleting, renaming, and moving files while they're being uploaded on MacOS. #123 also works for me. When I deleted a file while it was being uploaded, the upload was canceled.

**Comment by jasonwee** [comment]
work done in branch already merge, closing issue
