### ISSUE TITLE
sync-icon DLLs can't be deleted after registration in registry. 

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#72]
![image](https://user-images.githubusercontent.com/11735738/34631064-fbc154c6-f26e-11e7-9c64-c39d029ef6d8.png)

**Comment by MeijeSibbel** [comment]
can't delete "goobox-sync-storj-0.0.11-win64" due to registered overlay icons open in windows explorer. They sync app is not running.

**Comment by kaloyan-raev** [comment]
Could you try restarting the Windows Explorer? Then try deleting them again.

**Comment by MeijeSibbel** [comment]
I tried, multiple times actually, it doesn't work.

**Comment by kaloyan-raev** [comment]
So, if restarting the Explorer or Windows does not work, the only thing left is unregistering the DLLs (which may also require Explorer restart afterwards).

**Comment by MeijeSibbel** [comment]
Yeah, its strange though, maybe with the GUI move the files to user -> local -> goobox ?

**Comment by jkawamoto** [comment]
The GUI app hasn’t integrated the sync storj app yet.

**Comment by MeijeSibbel** [comment]
@jkawamoto , indeed, i think we should move these files to `local -> goobox` once it is integrated into the community-gui. Because it will be really frustrating for the user if they can't delete the installer directory.

**Comment by kaloyan-raev** [comment]
DLLs are usually installed in the Windows system directory, i.e. `C:\Windows\system32`.

**Comment by jkawamoto** [comment]
DLL registration in the Windows installer is still work in progress https://github.com/GooBox/goobox-community-gui/issues/57 but currently the installer copies DLLs in `C:\Program Files\Goobox\resources\libraries` and the uninstaller unregisters and deletes them. So users don't need to touch those directories.

**Comment by MeijeSibbel** [comment]
I think we can close this as this is fixed.
