### ISSUE TITLE
Return error when registering Storj account with invalid email or password

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-sync-storj#80]
Originally posted in https://github.com/GooBox/goobox-community-gui/issues/48

**Comment by kaloyan-raev** [comment]
It currently does.

Didn't you see this entries from the log?

```
Command result sent: {"status":"error","message":"Invalid email"}
```

```
Command result sent: {"status":"error","message":"Email is already registered"}
```

**Comment by jkawamoto** [comment]
So, this one isn't issue and we can close both of them, can't we? I think using other log level such as WARN or DEBUG is better to know which log entry is an issue or not.

**Comment by kaloyan-raev** [comment]
I am just saying the issue is not here. I am sure GUI v0.0.5 shows the error in a dialog. Perhaps, there is a regression in the GUI in the latest snapshot.

**Comment by MeijeSibbel** [comment]
I hink we can close this one as its already implemented.
