### ISSUE TITLE
Consider creating a encryption key if a user doesn't have one at login.

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#95]
Users signing up through app.storj.io don't have a encryption key, and thus they can't login through our app, as it won't allow the login without a key. And even if they create a key, they have to use it on at least one bucket for the community-gui to recognize it:

`2018-02-04 19:57:35 [Thread-0] DEBUG io.goobox.sync.storj.ipc.IpcExecutor - Command result sent: {"status":"error","message":"Encryption key cannot decrypt content"}`

 We should find a way to solve this. Related to https://github.com/GooBox/goobox-community-gui/issues/67

Right now i have to tell them to create a key with FileZilla and create the Goobox folder manually, this defeats the entire purpose of a user friendly app.

**Comment by kaloyan-raev** [comment]
If the account is empty (no buckets) then any encryption key will be accepted as valid.

Could the issue be for those users who created a bucket through the web app?

**Comment by MeijeSibbel** [comment]
Good question, i will test this and get back to you. Regarding the people registering through the web its definitely a issue, as they have no idea how and where (or eve what) to create a encryption key. That's also why i added a issue in community-GUI to add a generate seed button.

**Comment by MeijeSibbel** [comment]
So it looks like more and more people have a storj account at app.storj.io but don't have a private key, this is actually the majority of the early adopters. What do you think is the best way to solve this?

**Comment by kaloyan-raev** [comment]
Here is what we can do about this:

1. We implement https://github.com/GooBox/goobox-community-gui/issues/67 for those users who created their account on app.storj.io and have no encryption key yet
1. I modify the `Storj.verifyKeys()` method in java-libstorj in the following way:
   - if the account is not empty (there are buckets inside) and the provided encryption key fails decrypting _any_ of them, then another attempt will be made to decrypt _all_ existing buckets with an _empty_ encryption key.
   - if _all_ existing buckets can be decrypted with an empty encryption key then this means that they were created via app.storj.io and the app will accept the provided encryption key.
   - if _one or more_ buckets cannot be decrypted with an empty encryption key then this means that the user has generated an encryption key in the past and have used it with this account, but now tries to provide another encryption key. So the provided encryption key won't be accepted.

Opinions?

**Comment by MeijeSibbel** [comment]
Sounds good!, if users already created a bucket with a encryption key through FileZilla or Libstorj-CLI, we can assume they know how to manage their encryption keys and import it into the app.
